---
- name: Install and config fail2ban play
  #hosts: all
  #hosts: test
  hosts: roger
  become: 'True'
  tasks:
          - name: Update system package
            apt:
                    autoclean: 'True'
                    autoremove: 'True'
                    update_cache: 'True'
                    upgrade: 'True'

          - name: Install Fail2ban package
            apt:
                    name: fail2ban
                    state: present
            notify: restart fail2ban

          - name: Config Fail2ban
            template:
                    src: templates/fail2ban_jail.local.j2
                    dest: /etc/fail2ban/jail.local
                    group: root
                    owner: root
                    mode: 0644
            notify: restart fail2ban

          - name: Config ssh service
            template:
                    src: templates/fail2ban_custom_ssh.conf.j2
                    dest: /etc/fail2ban/jail.d/fail2ban_custom_ssh.conf
                    group: root
                    owner: root
                    mode: 0644
            notify: restart fail2ban

  handlers:
          - name: restart fail2ban
            service: name=fail2ban state=restarted
...
