---
- name: Install part
  remote_user: user
  hosts: roger
  #change to root
  vars:
          pachages:
  become: true
  become_method: sudo
  tasks:
          - name: update / upgrade
            apt:
                    update_cache: yes
                    upgrade: yes
                    state: latest

          - name: install sshd
            apt:
                    name: ssh
                    state: latest

          - name: insatll sudo
            apt:
                    name: sudo
                    state: latest

          - name: install fail2ban
            apt:
                    name: fail2ban
                    state: latest

          - name: install portsentry
            apt:
                    name: portsentry
                    state: latest

          - name: install mail
            apt:
                    name: "{{mail_stuff}}"
            vars:
                    mail_stuff:
                            - ssmtp
                            - mailutils

          - name: install web-serveur
            apt:
                    name: apache2
                    state: latest

          - name: clean serveur [useless packages/dependencies]
            apt:
                    autoclean: yes
                    autoremove: yes
