---
- name: Install and config portsentry
  hosts: test
  become: 'True'
  tasks:
          - name: Install package
            apt:
                    name: portsentry
                    state: present
            notify: restart portsentry

          - name: config portsentry mode
            replace:
                    path: /etc/default/portsentry
                    regexp: "{{ item.org }}"
                    replace: "{{ item.rep }}"
            with_items:
                    - { org: 'TCP_MODE="tcp"', rep: 'TCP_MODE="atcp"'}
                    - { org: 'UDP_MODE="udp"', rep: 'UDP_MODE="audp"'}
            notify: restart portsentry

          - name: config portsentry
            template:
                    src: templates/portsentry.conf.j2
                    dest: /etc/portsentry/portsentry.conf
            notify: restart portsentry


          - name: Setup service
            service:
                    name: portsentry
                    state: started
                    enabled: 'True'
            
  handlers:
          - name: restart portsentry
            service:
                    name: portsentry
                    state: restarted
...
