---
- name: Install and config portsentry
  hosts: all
  become: 'True'
  tasks:
          - name: Install package
            apt:
                    name: portsentry
                    state: present
            notify: restart portsentry


          - name: config portsentry mode
            replace:
                    path: /etc/default/portsentry
                    regexp: "{{ item.org }}"
                    replace: "{{ item.rep }}"
            with_items:
                    - { org: 'TCP_MODE="tcp"', rep: 'TCP_MODE="atcp"'}
                    - { org: 'UDP_MODE="udp"', rep: 'UDP_MODE="audp"'}
            notify: restart portsentry

          - name: config portsentry
            template:
                    src: templates/portsentry.conf.j2
                    dest: /etc/portsentry/portsentry.conf
            notify: restart portsentry

            #          - name: kill root
            #            lineinfile:
            #        src: /etc/portsentry/portsentry.conf
            #        line: 'KILL_HOSTS_DENY="ALL: $TARGET$ : DENY"'
            #        state: preset


            #          - name: config portsentry prod
            #            replace:
            #         path: /etc/portsentry/portsentry.conf
            #         regexp: "{{ item.org }}"
            #        replace: "{{ item.rep }}"
            #with_items:
            #        - { org: 'BLOCK_UDP="0"', rep: 'BLOCK_UDP="1"'}
            #        - { org: 'BLOCK_TCP="0"', rep: 'BLOCK_TCP="1"'}
            #        - { org: '#KILL_ROUTE="/sbin/iptables -I INPUT -s $TARGET$ -j DROP"', rep: 'KILL_ROUTE="/sbin/iptables -I INPUT -s $TARGET$ -j DROP"' }
            #notify: restart portsentry
                     

          - name: Setup service
            service:
                    name: portsentry
                    state: started
                    enabled: 'True'
            
  handlers:
          - name: restart portsentry
            service:
                    name: portsentry
                    state: restarted

...
