## ansible-playbook -i inventory set_raw_python.yml -K
---
- hosts: all
  gather_facts: False
  become_user: root
  become: true
  tasks:
          - name: install python3
            raw: "apt update -y && apt upgrade -y && apt install python3-pip -y"
            register: out

          - name: put out
            debug:
                    var: out
...
