---
- name: Config ssh service play
  #hosts: all
  hosts: test
  become: 'True'
  #hosts: roger
  tasks:

         - name: disable password authentification
            lineinfile:
                    dest: /etc/ssh/sshd_config
                    regexp: "{{ item.regexp }}"
                    line: "{{ item.line }} "
                    state: present
                    backup: 'True'
            loop:
                    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
                    - { regexp: "^PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
                    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
                    - { regexp: "^PubkeyAuthentication no", line: "PubkeyAuthentication yes" }
            notify:
                    restart ssh

  handlers:
          - name: restart ssh
            service: name=ssh state=restarted enabled=True
...
